# Extra settings for the Corne keyboard with displays

# Uncomment the following line to enable the Corne OLED Display
CONFIG_ZMK_DISPLAY=y

# Schedules display updates separately so as not to interfere with key scanning.
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
