// Definitions to use with configurations that require key positions instead of
// symbols
#define P_ESC 0
#define P_SQT 1
#define P_COMMA 2
#define P_DOT 3
#define P_P 4
#define P_Y 5
#define P_F 6
#define P_G 7
#define P_C 8
#define P_R 9
#define P_L 10
#define P_BKSP 11
#define P_TAB 12
#define P_A 13
#define P_O 14
#define P_E 15
#define P_U 16
#define P_I 17
#define P_D 18
#define P_H 19
#define P_T 20
#define P_N 21
#define P_S 22
#define P_ENTER 23
#define P_LSHFT 24
#define P_SEMI 25
#define P_Q 26
#define P_J 27
#define P_K 28
#define P_X 29
#define P_B 30
#define P_M 31
#define P_W 32
#define P_V 33
#define P_Z 34
#define P_RSHFT 35
#define P_ZAP 36
#define P_SPACE 37
#define P_EXTEND 38
#define P_THUMB_SHIFT 39
#define P_SYMBOL 40
#define P_MENU 41
