manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: hallettj
      url-base: https://github.com/hallettj
  projects:
    - name: zmk
      remote: hallettj
      revision: shifted_keys_workaround
      import: app/west.yml
  self:
    path: config
